# Label rules for PR auto-labeling
# See: https://github.com/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"
          - "**/*.md"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "uv.lock"
          - "requirements*.txt"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "docker-compose*.yml"
          - ".dockerignore"
